const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Đóng menu':'Mở menu');nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Mở menu')}));
const content={healthcare:{label:'HEALTHCARE',title:'Phát triển từ sự tận tâm.',description:'Khám phá hướng học tập và nghề nghiệp trong lĩnh vực chăm sóc sức khỏe. Buổi trao đổi bắt đầu từ nền tảng hiện tại và vai trò bạn muốn theo đuổi.',items:['Bằng cấp, chuyên ngành và kinh nghiệm chăm sóc hiện có.','Mục tiêu: học ngành mới, nâng cao chuyên môn hoặc tìm hiểu hướng nghề nghiệp.','Những yêu cầu về ngôn ngữ, công nhận bằng cấp và hành nghề cần kiểm tra theo nơi đến.'],field:0},beauty:{label:'BEAUTY & WELLNESS',title:'Để đam mê thành chuyên môn.',description:'Tìm hiểu hướng học tập và nâng cao tay nghề trong chăm sóc da, spa, wellness và dịch vụ làm đẹp.',items:['Kỹ năng, chứng chỉ và kinh nghiệm làm đẹp hiện có.','Lĩnh vực bạn muốn phát triển và mục tiêu học tập.','Nội dung đào tạo, phạm vi công việc và yêu cầu tại điểm đến cần được xem xét riêng.'],field:1},singapore:{label:'ĐIỂM ĐẾN / 01',title:'Singapore',description:'Một trong bốn thị trường trọng tâm của Lotus dành cho hành trình healthcare và làm đẹp.',items:['Xác định ngành và mục tiêu học tập hoặc nghề nghiệp.','Trao đổi về khả năng ngoại ngữ, ngân sách và thời gian dự kiến.','Tìm hiểu chương trình cụ thể trước khi quyết định.'],destination:0},canada:{label:'ĐIỂM ĐẾN / 02',title:'Canada',description:'Khởi đầu kế hoạch tại Canada bằng việc xác định lĩnh vực, địa phương và mục tiêu dài hạn của bạn.',items:['Chọn lĩnh vực healthcare hoặc beauty phù hợp với nền tảng hiện có.','Làm rõ tỉnh bang, ngôn ngữ và chương trình quan tâm.','Xem xét riêng mục tiêu học tập, nghề nghiệp và định cư.'],destination:1},europe:{label:'ĐIỂM ĐẾN / 03',title:'Châu Âu',description:'Châu Âu gồm nhiều quốc gia với ngôn ngữ và lộ trình khác nhau. Lotus bắt đầu từ việc giúp bạn làm rõ điểm đến mong muốn.',items:['Xác định quốc gia và ngôn ngữ bạn muốn theo học hoặc làm việc.','Trao đổi về chuyên ngành, bằng cấp và kinh nghiệm hiện có.','Lập danh sách chương trình và yêu cầu cần xác minh cho quốc gia cụ thể.'],destination:2}};
content.usa={label:'ĐIỂM ĐẾN / USA',title:'Mỹ · USA',description:'Từ nền tảng học tập tại Singapore, tìm hiểu hướng phát triển nghề nghiệp healthcare hoặc làm đẹp tại Mỹ.',items:['Đánh giá bằng cấp, ngoại ngữ và yêu cầu cấp phép theo nghề và tiểu bang.','Tìm hiểu công việc phù hợp và điều kiện xin thị thực riêng biệt.','Xem xét khả năng định cư và hồ sơ người thân theo chương trình cụ thể; không tự động phát sinh từ bằng cấp.'],destination:3};
const dialog=document.querySelector('#detail-dialog');
document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{const d=content[b.dataset.detail];document.querySelector('#dialog-label').textContent=d.label;document.querySelector('#dialog-title').textContent=d.title;document.querySelector('#dialog-description').textContent=d.description;const ul=document.querySelector('#dialog-list');ul.replaceChildren(...d.items.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));if(d.field!==undefined)document.querySelector('#field').selectedIndex=d.field;if(d.destination!==undefined)document.querySelector('#destination').selectedIndex=d.destination;dialog.showModal()}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());document.querySelector('#dialog-cta').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
let downloadUrl;document.querySelector('#plan-form').addEventListener('submit',e=>{e.preventDefault();const field=document.querySelector('#field').value,destination=document.querySelector('#destination').value;const text=`LOTUS GLOBAL IMMIGRATION\nGHI CHÚ CHUẨN BỊ TƯ VẤN\n\nLĩnh vực: ${field}\nĐiểm đến: ${destination}\n\nTôi cần chuẩn bị:\n- Trình độ học vấn và bằng cấp hiện có\n- Kinh nghiệm học tập hoặc làm việc\n- Khả năng ngoại ngữ\n- Ngân sách và thời điểm mong muốn\n- Câu hỏi về chương trình cụ thể\n\nĐây là ghi chú cá nhân, chưa được gửi đến Lotus.`;window.lotusNoteText=text;document.querySelector('#plan-summary').textContent=`${field} · ${destination}`;document.querySelector('#plan-result').hidden=false});
