const LOTUS_DATA=(()=>{try{return JSON.parse(document.querySelector('#lotus-data').textContent)}catch(e){return{details:{}}}})();
const EN=document.documentElement.lang==='en',MENU_OPEN=EN?'Open menu':'Mở menu',MENU_CLOSE=EN?'Close menu':'Đóng menu';
const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?MENU_CLOSE:MENU_OPEN);nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label',MENU_OPEN)}));
const content=LOTUS_DATA.details||{};
const dialog=document.querySelector('#detail-dialog');
document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{const d=content[b.dataset.detail];if(!d)return;document.querySelector('#dialog-label').textContent=d.label;document.querySelector('#dialog-title').textContent=d.title;document.querySelector('#dialog-description').textContent=d.description;const ul=document.querySelector('#dialog-list');ul.replaceChildren(...d.items.map(t=>{const li=document.createElement('li');li.textContent=t;return li}));window.__lotusPreset={field:d.field,destination:d.destination,destinationValue:d.destinationValue};dialog.showModal()}));
document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());document.querySelector('#dialog-cta').addEventListener('click',()=>{dialog.close();if(window.lotusForm&&window.__lotusPreset)window.lotusForm.preset(window.__lotusPreset)});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
